spring:
  h2.console.enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:F:\completableFutureFromGit\mypractiseRepo\completablefutureex\src\main\resources\asyncfuturetest.db
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false

server:
  port: 9292

